//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keyboard_configuration_software.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apex")]
        public string Gamelists0 {
            get {
                return ((string)(this["Gamelists0"]));
            }
            set {
                this["Gamelists0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM20")]
        public string SerialPort {
            get {
                return ((string)(this["SerialPort"]));
            }
            set {
                this["SerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("theHunter")]
        public string Gamelists1 {
            get {
                return ((string)(this["Gamelists1"]));
            }
            set {
                this["Gamelists1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bsg")]
        public string Gamelists2 {
            get {
                return ((string)(this["Gamelists2"]));
            }
            set {
                this["Gamelists2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EscapeFromTarkov")]
        public string Gamelists3 {
            get {
                return ((string)(this["Gamelists3"]));
            }
            set {
                this["Gamelists3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minecraft")]
        public string Gamelists4 {
            get {
                return ((string)(this["Gamelists4"]));
            }
            set {
                this["Gamelists4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arduino")]
        public string Codinglists0 {
            get {
                return ((string)(this["Codinglists0"]));
            }
            set {
                this["Codinglists0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PUBG")]
        public string Gamelists5 {
            get {
                return ((string)(this["Gamelists5"]));
            }
            set {
                this["Gamelists5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists6 {
            get {
                return ((string)(this["Gamelists6"]));
            }
            set {
                this["Gamelists6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists7 {
            get {
                return ((string)(this["Gamelists7"]));
            }
            set {
                this["Gamelists7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists8 {
            get {
                return ((string)(this["Gamelists8"]));
            }
            set {
                this["Gamelists8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists9 {
            get {
                return ((string)(this["Gamelists9"]));
            }
            set {
                this["Gamelists9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists10 {
            get {
                return ((string)(this["Gamelists10"]));
            }
            set {
                this["Gamelists10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists1 {
            get {
                return ((string)(this["Codinglists1"]));
            }
            set {
                this["Codinglists1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists2 {
            get {
                return ((string)(this["Codinglists2"]));
            }
            set {
                this["Codinglists2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists3 {
            get {
                return ((string)(this["Codinglists3"]));
            }
            set {
                this["Codinglists3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists4 {
            get {
                return ((string)(this["Codinglists4"]));
            }
            set {
                this["Codinglists4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists5 {
            get {
                return ((string)(this["Codinglists5"]));
            }
            set {
                this["Codinglists5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists6 {
            get {
                return ((string)(this["Codinglists6"]));
            }
            set {
                this["Codinglists6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists7 {
            get {
                return ((string)(this["Codinglists7"]));
            }
            set {
                this["Codinglists7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists8 {
            get {
                return ((string)(this["Codinglists8"]));
            }
            set {
                this["Codinglists8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists9 {
            get {
                return ((string)(this["Codinglists9"]));
            }
            set {
                this["Codinglists9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists10 {
            get {
                return ((string)(this["Codinglists10"]));
            }
            set {
                this["Codinglists10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists11 {
            get {
                return ((string)(this["Gamelists11"]));
            }
            set {
                this["Gamelists11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists12 {
            get {
                return ((string)(this["Gamelists12"]));
            }
            set {
                this["Gamelists12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists13 {
            get {
                return ((string)(this["Gamelists13"]));
            }
            set {
                this["Gamelists13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists14 {
            get {
                return ((string)(this["Gamelists14"]));
            }
            set {
                this["Gamelists14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists15 {
            get {
                return ((string)(this["Gamelists15"]));
            }
            set {
                this["Gamelists15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists16 {
            get {
                return ((string)(this["Gamelists16"]));
            }
            set {
                this["Gamelists16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string Gamelists17 {
            get {
                return ((string)(this["Gamelists17"]));
            }
            set {
                this["Gamelists17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists18 {
            get {
                return ((string)(this["Gamelists18"]));
            }
            set {
                this["Gamelists18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists19 {
            get {
                return ((string)(this["Gamelists19"]));
            }
            set {
                this["Gamelists19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists20 {
            get {
                return ((string)(this["Gamelists20"]));
            }
            set {
                this["Gamelists20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists21 {
            get {
                return ((string)(this["Gamelists21"]));
            }
            set {
                this["Gamelists21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists22 {
            get {
                return ((string)(this["Gamelists22"]));
            }
            set {
                this["Gamelists22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists23 {
            get {
                return ((string)(this["Gamelists23"]));
            }
            set {
                this["Gamelists23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists24 {
            get {
                return ((string)(this["Gamelists24"]));
            }
            set {
                this["Gamelists24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists25 {
            get {
                return ((string)(this["Gamelists25"]));
            }
            set {
                this["Gamelists25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists26 {
            get {
                return ((string)(this["Gamelists26"]));
            }
            set {
                this["Gamelists26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists27 {
            get {
                return ((string)(this["Gamelists27"]));
            }
            set {
                this["Gamelists27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists28 {
            get {
                return ((string)(this["Gamelists28"]));
            }
            set {
                this["Gamelists28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists29 {
            get {
                return ((string)(this["Gamelists29"]));
            }
            set {
                this["Gamelists29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Gamelists30 {
            get {
                return ((string)(this["Gamelists30"]));
            }
            set {
                this["Gamelists30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists11 {
            get {
                return ((string)(this["Codinglists11"]));
            }
            set {
                this["Codinglists11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists12 {
            get {
                return ((string)(this["Codinglists12"]));
            }
            set {
                this["Codinglists12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists13 {
            get {
                return ((string)(this["Codinglists13"]));
            }
            set {
                this["Codinglists13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists14 {
            get {
                return ((string)(this["Codinglists14"]));
            }
            set {
                this["Codinglists14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists15 {
            get {
                return ((string)(this["Codinglists15"]));
            }
            set {
                this["Codinglists15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists16 {
            get {
                return ((string)(this["Codinglists16"]));
            }
            set {
                this["Codinglists16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists17 {
            get {
                return ((string)(this["Codinglists17"]));
            }
            set {
                this["Codinglists17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists18 {
            get {
                return ((string)(this["Codinglists18"]));
            }
            set {
                this["Codinglists18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists19 {
            get {
                return ((string)(this["Codinglists19"]));
            }
            set {
                this["Codinglists19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists20 {
            get {
                return ((string)(this["Codinglists20"]));
            }
            set {
                this["Codinglists20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists21 {
            get {
                return ((string)(this["Codinglists21"]));
            }
            set {
                this["Codinglists21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists22 {
            get {
                return ((string)(this["Codinglists22"]));
            }
            set {
                this["Codinglists22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists23 {
            get {
                return ((string)(this["Codinglists23"]));
            }
            set {
                this["Codinglists23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists24 {
            get {
                return ((string)(this["Codinglists24"]));
            }
            set {
                this["Codinglists24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists25 {
            get {
                return ((string)(this["Codinglists25"]));
            }
            set {
                this["Codinglists25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists26 {
            get {
                return ((string)(this["Codinglists26"]));
            }
            set {
                this["Codinglists26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists27 {
            get {
                return ((string)(this["Codinglists27"]));
            }
            set {
                this["Codinglists27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists28 {
            get {
                return ((string)(this["Codinglists28"]));
            }
            set {
                this["Codinglists28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists29 {
            get {
                return ((string)(this["Codinglists29"]));
            }
            set {
                this["Codinglists29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string Codinglists30 {
            get {
                return ((string)(this["Codinglists30"]));
            }
            set {
                this["Codinglists30"] = value;
            }
        }
    }
}
